spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    data-password:
    data-username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
security:
  basic:
    enabled: true
  user:
    password: admin
    name: admin
  headers:
    frame: false
logging:
  level: trace